<?php


return [
   'powershell' => 'powershell',
   'php' => [
       'php',
       'php-date',
       'php-libxml',
       'php-openssl',
       'php-pcre',
       'php-zlib',
       'php-filter',
       'php-hash',
       'php-readline',
       'php-spl',
       'php-session',
       'php-standard',
       'php-bcmath',
       'php-calendar',
       'php-ctype',
       'php-curl',
       'php-dom',
       'php-mbstring',
       'php-fileinfo',
       'php-gd',
       'php-iconv',
       'php-intl',
       'php-json',
       'php-ldap',
       'php-mysqlnd',
       'php-pdo',
       'php-pgsql',
       'php-tokenizer',
       'php-xml',
       'php-xmlwriter',
       'php-xsl',
       'php-pdo_mysql',
       'php-mysqli',
       'php-pdo_pgsql',
       'php-xmlreader',
       'php-zip',
   ],
   'other' => 'mailx nano htop unzip zip nodejs php MariaDB MariaDB-server MariaDB-common MariaDB-client MariaDB-compat postgresql15 postgresql15-server postgresql15-contrib',
];
